### ISSUE TITLE
unifiedviews-webapp-mysql: frontend.theme is missing in frontend.config

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Packages#29]
```
2015-03-11 14:47:11,152 [localhost-startStop-1] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'moduleFacade': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacadeConfig cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.configuration; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [cz.cuni.mff.xrg.odcs.frontend.${frontend.theme}] for bean with name 'ui' defined in ServletContext resource [/WEB-INF/classes/frontend-context.xml]; nested exception is java.lang.ClassNotFoundException: cz.cuni.mff.xrg.odcs.frontend.${frontend.theme}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:287) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1106) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:607) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:282) ~[spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:204) ~[spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4790) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5284) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582) [tomcat-catalina-7.0.28.jar:7.0.28]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacadeConfig cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.configuration; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [cz.cuni.mff.xrg.odcs.frontend.${frontend.theme}] for bean with name 'ui' defined in ServletContext resource [/WEB-INF/classes/frontend-context.xml]; nested exception is java.lang.ClassNotFoundException: cz.cuni.mff.xrg.odcs.frontend.${frontend.theme}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:513) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:92) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:284) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        ... 26 common frames omitted
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [cz.cuni.mff.xrg.odcs.frontend.${frontend.theme}] for bean with name 'ui' defined in ServletContext resource [/WEB-INF/classes/frontend-context.xml]; nested exception is java.lang.ClassNotFoundException: cz.cuni.mff.xrg.odcs.frontend.${frontend.theme}
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1262) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1331) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:337) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:316) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:187) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:856) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:813) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:730) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:485) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        ... 28 common frames omitted
Caused by: java.lang.ClassNotFoundException: cz.cuni.mff.xrg.odcs.frontend.${frontend.theme}
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1711) ~[tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1556) ~[tomcat-catalina-7.0.28.jar:7.0.28]
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:258) ~[spring-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:417) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1283) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1254) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        ... 37 common frames omitted
```

**Comment by Jan-Marcek** [comment]
fixed
