### ISSUE TITLE
Problem installing the 2.0.1 Packages

### ISSUE THREAD

**Issue by paulmassey42** [UnifiedViews/Packages#30]
I'm trying to build a VM with unifiedviews preinstalled. The setup I was using can be found in:
       https://github.com/paulmassey42/VagrantUnifiedViews2.x
This is based on a previous one (for 1.5.5). So this is a fresh wheezy (via vagrant). I'm seeing the following in /var/logs/unifiedviews/frontend/catalina.out file.

What am I missing?

Paul.
-------------------
13:03:10.152 [localhost-startStop-1] ERROR o.s.w.c.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestSingleLogo
utFilter' defined in ServletContext resource [/WEB-INF/classes/cas-context-security.xml]: Instantiation o
f bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instan
tiate bean class [org.springframework.security.web.authentication.logout.LogoutFilter]: Constructor threw
 exception; nested exception is java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redir
ect URL
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorR
esolver.java:288) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstruct
or(AbstractAutowireCapableBeanFactory.java:1035) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstanc
e(AbstractAutowireCapableBeanFactory.java:939) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(Abst
ractAutowireCapableBeanFactory.java:485) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(Abstra
ctAutowireCapableBeanFactory.java:456) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.
java:294) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSin
gletonBeanRegistry.java:225) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.ja
va:291) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java
:193) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(
DefaultListableBeanFactory.java:607) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization
(AbstractApplicationContext.java:925) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationCont
ext.java:472) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:2
82) ~[spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:204
) ~[spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener
.java:47) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4790) [tomcat-cata
lina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5284) [tomcat-cata
lina-7.0.28.jar:7.0.28]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-catalina-7.0.28.j
ar:7.0.28]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899) [tomcat-catali
na-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875) [tomcat-catalina-7.0.2
8.jar:7.0.28]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618) [tomcat-catalina-7.0.28.
jar:7.0.28]
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650) [tomcat-catalina-
7.0.28.jar:7.0.28]
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582) [tomcat-cata
lina-7.0.28.jar:7.0.28]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.sp
ringframework.security.web.authentication.logout.LogoutFilter]: Constructor threw exception; nested excep
tion is java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redirect URL
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:162) ~[spring-beans-3.1.4.
RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstan
tiationStrategy.java:121) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorR
esolver.java:280) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        ... 27 common frames omitted
Caused by: java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redirect URL
------------------------------------------

**Comment by skrchnavy** [comment]
Hi Paul.

This issue is caused by dependency that was added into the code but is 
not properly setup in the package.
The dependency will be removed (it shall not be present in default 
setup) and new release will be provided.

Best regards.
Sveto.
